site_name: "2021 SANS HHC Write-Up"
site_author: Thomas Bouve
site_url: https://n00.be/HolidayHackChallenge2021/
copyright: Copyright &copy; 2021 <a href="https://n00.be">Thomas Bouve</a>
theme:
  icon:
    # logo: fontawesome/regular/snowflake
    # logo: fontawesome/solid/sleigh
    # logo: fontawesome/solid/tree
    # logo: fontawesome/solid/candy-cane
    logo: fontawesome/solid/rocket
  name: material
  favicon: img/misc/favicon.ico
  features:
    - navigation.instant
    - toc.integrate
    #- navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.instant
    #- navigation.sections
    #- navigation.expand
  palette:
    scheme: default
    primary: darkblue
    accent: darkblue
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/crahan
      name: CraHan on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/crahan
      name: CraHan on GitHub
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/crahan/
      name: CraHan on Instagram
extra_css:
  - css/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/tablesort.js
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - meta
  - footnotes
  - def_list
  - toc:
      permalink: ⚓︎
      toc_depth: 2
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
- Welcome: 'index.md'
- Objectives:
  - Where is Caramel Santaigo?: 'objectives/o2.md'
  - Thaw Frost Tower's Entrance: 'objectives/o3.md'
  - Slot Machine Investigation: 'objectives/o4.md'
  - Strange USB Device: 'objectives/o5.md'
  - Shellcode Primer: 'objectives/o6.md'
  - Printer Exploitation: 'objectives/o7.md'
  - Kerberoasting on an Open Fire: 'objectives/o8.md'
  - Splunk!: 'objectives/o9.md'
  - Now Hiring!: 'objectives/o10.md'
  - Customer Complaint Analysis: 'objectives/o11.md'
  - Frost Tower Website Checkup: 'objectives/o12.md'
  - FPGA Programming: 'objectives/o13.md'
- Terminal Hints:
  - Exif Metadata: 'hints/h2.md'
  - Grepping for Gold: 'hints/h3.md'
  - Logic Munchers: 'hints/h4.md'
  - IPv6 Sandbox: 'hints/h5.md'
  - Holiday Hero: 'hints/h6.md'
  - HoHo... No: 'hints/h8.md'
  - Yara Analysis: 'hints/h9.md'
  - IMDS Exploration: 'hints/h10.md'
  - Strace Ltrace Retrace: 'hints/h11.md'
  - The Elf C0de: 'hints/h12.md'
  - Frostavator: 'hints/h13.md'
- Easter Eggs: 'easter_eggs.md'
